name: Build Image

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Build Image
        runs-on: ubuntu-latest
        timeout-minutes: 120
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/create-3d-icon:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/create-3d-icon:${{ github.sha }}
                  platforms: linux/amd64,linux/arm64
